# Generated by Django 4.1.3 on 2022-11-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='zip_code',
            new_name='phone_num',
        ),
    ]
