# Generated by Django 4.1.3 on 2023-01-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_zip_code_ordermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
